MCP_ZOHO_LOGIN_CLIENT_ID=1000.PYZBKVHC0WNMO5EPOFDYDRVJD20CCR
MCP_ZOHO_LOGIN_CLIENT_SECRET=568de9ca9d6fce9c1992f9f3040247ca0bd602c55e
MCP_ZOHO_LOGIN_REDIRECT_URI=http://localhost:8080/trade-show-team-project/oauth-callback.html
MCP_ZOHO_LOGIN_BASE_URL=https://accounts.zoho.in
